/**
 * aoc4_live_autofill.js
 * 
 * Auto-generated by AOC-4 eform CLI.
 * Injects client figures and metadata into the live MCA V3 form using guideBridge.
 */

(function() {
  console.clear();
  console.log("%c[AOC-4 AutoFill] Starting Live Form Infill...", "color: #1a73e8; font-weight: bold; font-size: 16px;");

  // Master Data Dictionary
  const FIELDS = __FIELDS_JSON__;

  const RADIO_MAP = {
    'Yes': '-1_widget', 'No': '-2_widget', 'NA': '-3_widget',
    'Firm': '-2_widget', 'Individual': '-1_widget', 'Original': '-1_widget'
  };

  let countFilled = 0;
  let countSkipped = 0;
  let countNotFound = 0;

  function fillField(className, val) {
    if (val === 'XXXX') {
      console.log(`%c[Skip Placeholder] ${className} left blank for manual input`, 'color: #ff9800;');
      countSkipped++;
      return;
    }

    const wrapper = document.getElementsByClassName(className)[0];
    if (!wrapper) {
      console.warn(`[Not Found] Wrapper class .${className} was not found on the page.`);
      countNotFound++;
      return;
    }

    let aemSuccess = false;

    // --- 1. AEM guideBridge Model Infill ---
    if (window.guideBridge) {
      const som = wrapper.getAttribute('data-guide-view-bind');
      if (som) {
        try {
          const node = window.guideBridge.resolveNode(som);
          if (node) {
            node.value = val;
            console.log(`%c[AEM Model] Set ${className} = "${val}"`, 'color: #4caf50;');
            aemSuccess = true;
          }
        } catch (e) {
          console.warn(`[AEM Model Error] Failed to set ${className} via guideBridge:`, e);
        }
      }
    }

    // --- 2. DOM Fallback & UI Sync ---
    // Dropdown Select
    const select = wrapper.querySelector('select');
    if (select) {
      let foundOption = false;
      for (let i = 0; i < select.options.length; i++) {
        if (select.options[i].value === val || select.options[i].text.trim() === val) {
          select.value = select.options[i].value;
          foundOption = true;
          break;
        }
      }
      if (!foundOption) {
        console.log(`[Adding Option] Dynamic option added to select under .${className}: ${val}`);
        const opt = document.createElement('option');
        opt.value = val;
        opt.text = val;
        opt.selected = true;
        select.appendChild(opt);
        select.value = val;
      }
      try { select.dispatchEvent(new Event('change', { bubbles: true })); } catch(e) {}
      countFilled++;
      return;
    }

    // Radio Buttons
    const radio = wrapper.querySelector('input[type="radio"]');
    if (radio) {
      const suffix = RADIO_MAP[val];
      if (suffix) {
        const radios = wrapper.querySelectorAll('input[type="radio"]');
        let matched = false;
        for (let i = 0; i < radios.length; i++) {
          if (radios[i].id.endsWith(suffix)) {
            radios[i].checked = true;
            try { radios[i].dispatchEvent(new Event('change', { bubbles: true })); } catch(e) {}
            matched = true;
            break;
          }
        }
        if (matched) {
          countFilled++;
          return;
        }
      }
    }

    // Text Box or Text Area
    const input = wrapper.querySelector('input, textarea');
    if (input) {
      input.value = val;
      try { input.dispatchEvent(new Event('change', { bubbles: true })); } catch(e) {}
      try { input.dispatchEvent(new Event('input', { bubbles: true })); } catch(e) {}
      try { input.dispatchEvent(new Event('blur', { bubbles: true })); } catch(e) {}
      countFilled++;
      return;
    }

    if (aemSuccess) {
      countFilled++;
      return;
    }

    console.warn(`[No Input Element] Found wrapper class .${className} but no input/textarea/select inside.`);
    countNotFound++;
  }

  // Iterate over all fields
  for (const className in FIELDS) {
    fillField(className, FIELDS[className]);
  }

  // Summary Report
  console.log("%c\n── Autofill Summary Report ──────────────────────────", "font-weight: bold; color: #1a73e8;");
  console.log(`  Fields Filled successfully : ${countFilled}`);
  console.log(`  Placeholders skipped (XXXX): ${countSkipped}`);
  console.log(`  Fields not found on page   : ${countNotFound}`);
  console.log("─────────────────────────────────────────────────────");
  console.log("%c[AOC-4 AutoFill] Finished. Please inspect the page and manually fill in the missing fields (e.g. Auditor PAN, ADT-1 SRN).", "color: #4caf50; font-weight: bold;");
})();
