'use strict';

/**
 * CIRP Statutory Timeline Engine
 * -------------------------------
 * Calculates mandatory IBBI statutory milestones from Admission Date (T_0)
 * to T_180 / T_330 and generates native Mermaid.js Gantt charts (`timeline.md`).
 */

const fs = require('fs');
const path = require('path');

const STATUTORY_MILESTONES = [
    { key: 't0_admission', day: 0, title: 'Admission Date (T0)', section: 'Pre-CoC' },
    { key: 'public_announcement', day: 3, title: 'Public Announcement (Form A)', section: 'Pre-CoC' },
    { key: 'claims_deadline', day: 14, title: 'Claims Submission Deadline', section: 'Pre-CoC' },
    { key: 'coc_constitution', day: 23, title: 'CoC Constitution', section: 'Pre-CoC' },
    { key: 'first_coc_meeting', day: 30, title: 'First CoC Meeting / RP Confirmation', section: 'CoC & Process' },
    { key: 'information_memorandum', day: 54, title: 'Information Memorandum (IM)', section: 'CoC & Process' },
    { key: 'publish_form_g_eoi', day: 75, title: 'Publish Form G (EOI)', section: 'Resolution Phase' },
    { key: 'issue_rfrp', day: 105, title: 'Issue RFRP & Evaluation Matrix', section: 'Resolution Phase' },
    { key: 'plan_submission_coc', day: 135, title: 'Resolution Plan Submission by PRAs', section: 'Resolution Phase' },
    { key: 'coc_plan_approval', day: 165, title: 'CoC Vote on Resolution Plan', section: 'Resolution Phase' },
    { key: 'cirp_completion_180', day: 180, title: '180-Day Statutory CIRP Limit', section: 'Statutory Limits' },
    { key: 'max_cirp_completion_330', day: 330, title: '330-Day Outer Mandatory Limit', section: 'Statutory Limits' }
];

function addDays(dateStr, days) {
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) return new Date();
    d.setDate(d.getDate() + days);
    return d;
}

function formatDate(dateObj) {
    const year = dateObj.getFullYear();
    const month = String(dateObj.getMonth() + 1).padStart(2, '0');
    const day = String(dateObj.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
}

/**
 * Calculates all statutory CIRP milestone dates given T0.
 */
function calculateCirpTimeline(t0DateStr = new Date().toISOString().split('T')[0]) {
    const t0 = new Date(t0DateStr);
    const validT0Str = isNaN(t0.getTime()) ? formatDate(new Date()) : formatDate(t0);

    return STATUTORY_MILESTONES.map(m => {
        const targetDateObj = addDays(validT0Str, m.day);
        const targetDateStr = formatDate(targetDateObj);
        const now = new Date();
        let status = 'upcoming';
        if (now > targetDateObj) status = 'passed';
        else if ((targetDateObj - now) / (1000 * 60 * 60 * 24) <= 7) status = 'due_soon';

        return {
            ...m,
            targetDate: targetDateStr,
            status
        };
    });
}

/**
 * Generates Mermaid.js Gantt chart Markdown for timeline.md.
 */
function generateMermaidTimeline(t0DateStr, caseId = 'CIRP Case') {
    const milestones = calculateCirpTimeline(t0DateStr);
    const t0Formatted = milestones[0].targetDate;

    let md = `# 📅 CIRP Statutory Timeline ($T_0 \\rightarrow T_{330}$)\n\n`;
    md += `**Case ID**: \`${caseId}\`  \n`;
    md += `**Admission Date ($T_0$)**: \`${t0Formatted}\`  \n`;
    md += `**180-Day Target**: \`${milestones.find(m => m.key === 'cirp_completion_180').targetDate}\`  \n`;
    md += `**330-Day Outer Limit**: \`${milestones.find(m => m.key === 'max_cirp_completion_330').targetDate}\`  \n\n`;

    md += `## 📊 Interactive Gantt Chart\n\n`;
    md += `\`\`\`mermaid\ngantt\n`;
    md += `    title CIRP Compliance Calendar (T0: ${t0Formatted})\n`;
    md += `    dateFormat  YYYY-MM-DD\n`;
    md += `    axisFormat  %b %d\n\n`;

    let currentSection = '';
    milestones.forEach((m, idx) => {
        if (m.section !== currentSection) {
            currentSection = m.section;
            md += `    section ${currentSection}\n`;
        }

        const tag = m.status === 'passed' ? ':done, ' : m.status === 'due_soon' ? ':crit, active, ' : ':active, ';
        const nextMilestone = milestones[idx + 1];
        const endDate = nextMilestone ? nextMilestone.targetDate : addDays(m.targetDate, 5).toISOString().split('T')[0];

        md += `    ${m.title} (T+${m.day}) ${tag}${m.targetDate}, ${endDate}\n`;
    });

    md += `\`\`\`\n\n`;

    md += `## 📋 Statutory Milestone Schedule\n\n`;
    md += `| Milestone | Code Ref | Day | Target Date | Status |\n`;
    md += `| :--- | :--- | :---: | :---: | :---: |\n`;
    milestones.forEach(m => {
        const badge = m.status === 'passed' ? '✅ Completed' : m.status === 'due_soon' ? '⚠️ Due Soon' : '⏳ Upcoming';
        md += `| ${m.title} | Reg ${m.day} | T+${m.day} | \`${m.targetDate}\` | ${badge} |\n`;
    });

    md += `\n*Auto-generated by Hayagriva Timeline Engine.*\n`;
    return md;
}

/**
 * Ensures timeline.md exists in caseDir.
 */
function updateWorkspaceTimeline(caseDir, t0DateStr = null) {
    try {
        const manifestPath = path.join(caseDir, 'case_manifest.json');
        let caseId = path.basename(caseDir);
        let t0 = t0DateStr || formatDate(new Date());

        if (fs.existsSync(manifestPath)) {
            try {
                const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
                if (manifest.caseId) caseId = manifest.caseId;
                if (manifest.t0_admission_date) t0 = manifest.t0_admission_date;
            } catch (_) {}
        }

        const timelineContent = generateMermaidTimeline(t0, caseId);
        const timelinePath = path.join(caseDir, 'timeline.md');
        fs.writeFileSync(timelinePath, timelineContent, 'utf8');
        console.log(`[Timeline Engine] timeline.md written for ${caseDir}`);
    } catch (e) {
        console.error(`[Timeline Engine] Failed to write timeline.md: ${e.message}`);
    }
}

module.exports = { calculateCirpTimeline, generateMermaidTimeline, updateWorkspaceTimeline, STATUTORY_MILESTONES };
