// backend/tests/test_license_envelope_formats.test.js
'use strict';

const assert = require('assert');
const crypto = require('crypto');
const { validateLicenseEnvelope, generateLicenseKey } = require('../lib/utils/license-validator');

const testSecret = 'hayagriva_sovereign_chamber_secret_key_2026';

const payload = {
    sub: 'advocate.sharma@nclt.in',
    tier: 'starter',
    valid_until: new Date(Date.now() + 30 * 86400000).toISOString(),
    hardwareFingerprint: 'MAC-A1B2C3D4E5F6'
};

// 1. Test 2-part format generated by cloud portal: <payloadB64>.<sigB64>
const pB64 = Buffer.from(JSON.stringify(payload)).toString('base64url');
const sigB64 = crypto.createHmac('sha256', testSecret).update(pB64).digest('base64url');
const twoPartToken = `${pB64}.${sigB64}`;

const resTwoPart = validateLicenseEnvelope(twoPartToken);
assert.strictEqual(resTwoPart.valid, true, '2-part token must be valid');
assert.strictEqual(resTwoPart.tier, 'starter');
assert.strictEqual(resTwoPart.payload.sub, 'advocate.sharma@nclt.in');

// 2. Test 3-part legacy format: HAYG.<payloadB64>.<sigB64>
const threePartToken = `HAYG.${pB64}.${sigB64}`;
const resThreePart = validateLicenseEnvelope(threePartToken);
assert.strictEqual(resThreePart.valid, true, '3-part token must be valid');
assert.strictEqual(resThreePart.tier, 'starter');

console.log('✓ Task 1: 2-part and 3-part envelope verification passed cleanly');
